

version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: my-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dbdev
      POSTGRES_USER: dbdev
      POSTGRES_DB: dbdev
      # POSTGRES_INITDB_OPTIONS: "--encoding=UTF8 --locale=en_US.utf8"
      POSTGRES_INITDB_OPTIONS: "--encoding=UTF8"
    restart: always
  vpn-manager:
    build:
      context: .
      dockerfile: Dockerfile
    image: vpn-manager
    container_name: vpn-manager
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: always
    environment:
      - DATABASE_URL=postgresql://dbdev:dbdev@postgres:5432/dbdev
      - PORT=3000
      - AUTH_SECRET= mysecret
      - L2TP-PRESHARED-KEY= my-l2tp-secret-key
      - AUTH_TRUST_HOST= true
volumes:
  postgres_data:
    driver: local
